CREATE INDEX dtb_products_class_product_id_key ON dtb_products_class(product_id);
CREATE INDEX dtb_order_detail_product_id_key ON dtb_order_detail(product_id);
CREATE INDEX dtb_category_category_id_key ON dtb_category(category_id);

INSERT INTO dtb_member (name, login_id, password, creator_id, authority, work, del_flg, create_date, update_date)
VALUES ('dummy','dummy',' ',0,0,1,1, now(), now());

insert into dtb_bloc ( bloc_name, tpl_path, filename, php_path, del_flg, create_date, update_date ) values ('范畴',	'bloc/category.tpl', 'category','frontparts/bloc/category.php', 1, now(), now());
insert into dtb_bloc ( bloc_name, tpl_path, filename, php_path, del_flg, create_date, update_date ) values ('利用向导','bloc/guide.tpl', 'guide','', 1, now(), now());
insert into dtb_bloc ( bloc_name, tpl_path, filename, php_path, del_flg, create_date, update_date ) values ('进入购物手推车的商品',	'bloc/cart.tpl', 'cart','frontparts/bloc/cart.php', 1, now(), now());
insert into dtb_bloc ( bloc_name, tpl_path, filename, php_path, del_flg, create_date, update_date ) values ('商品检索',	'bloc/search_products.tpl', 'search_products','frontparts/bloc/search_products.php', 1, now(), now());
insert into dtb_bloc ( bloc_name, tpl_path, filename, php_path, del_flg, create_date, update_date ) values ('新到信息',	'bloc/news.tpl', 'news','frontparts/bloc/news.php', 1, now(), now());
insert into dtb_bloc ( bloc_name, tpl_path, filename, php_path, del_flg, create_date, update_date ) values ('登录',	'bloc/login.tpl', 'login','frontparts/bloc/login.php', 1, now(), now());
insert into dtb_bloc ( bloc_name, tpl_path, filename, php_path, del_flg, create_date, update_date ) values ('推荐商品', 'bloc/best5.tpl', 'best5','frontparts/bloc/best5.php', 1, now(), now());

insert into dtb_pagelayout (page_name,url,php_dir,tpl_dir,filename,edit_flg, create_date, update_date)values('TOP页','index.php',' ','user_data/templates/','top',2,now(),now());
insert into dtb_pagelayout (page_name,url,php_dir,tpl_dir,filename,edit_flg, create_date, update_date)values('商品一览页','products/list.php',' ','user_data/templates/','list',2,now(),now());
insert into dtb_pagelayout (page_name,url,php_dir,tpl_dir,filename,edit_flg, create_date, update_date)values('商品详细页','products/detail.php',' ','user_data/templates/','detail',2,now(),now());
insert into dtb_pagelayout (page_name,url,php_dir,tpl_dir,filename,edit_flg, create_date, update_date)values('我的页','mypage/index.php',' ','','',2,now(),now());

insert into dtb_pagelayout (page_id,page_name,url, create_date, update_date)values(0, '预览',' ',now(),now());
update dtb_pagelayout set page_id = 0 where page_id = 5;

INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(1,1,1,2,'category');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(1,1,2,3,'guide');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(1,1,3,1,'cart');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(1,3,4,2,'search_products');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(1,4,5,1,'news');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(1,3,6,1,'login');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(1,4,7,2,'best5');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(2,1,1,2,'category');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(2,1,2,3,'guide');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(2,1,3,1,'cart');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(2,5,4,0,'search_products');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(2,5,5,0,'news');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(2,5,6,0,'login');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(2,5,7,0,'best5');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(3,1,1,2,'category');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(3,1,2,3,'guide');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(3,1,3,1,'cart');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(3,5,4,0,'search_products');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(3,5,5,0,'news');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(3,5,6,0,'login');
INSERT INTO dtb_blocposition (page_id,target_id,bloc_id,bloc_row,filename)values(3,5,7,0,'best5');

insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'product_id','商品ID',1,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'product_class_id','规格ID',2,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'classcategory_id1','规格名1',3,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'classcategory_id2','规格名2',4,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'name','商品名称',5,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'status','公开标志',6,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'product_flag','商品状态',7,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'product_code','商品编码',8,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'price01','通常价格',9,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'price02','销售价格',10,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'stock','库存数',11,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'deliv_fee','运费',12,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'point_rate','点给予率',13,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sale_limit','购买限制',14,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'comment1','制造厂URL',15,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'comment3','检索语',16,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'main_list_comment','一览-主要评语',17,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'main_list_image','一览-主要画像',18,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'main_comment','详细-主要评语',19,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'main_image','详细-主要画像',20,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'main_large_image','详细-主要扩大画像 ',21,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'file1','颜色比较画像',22,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'file2','商品详细文件',23,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_title1','详细-副标题（1）',24,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_comment1','详细-辅助评语（1）',25,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_image1','详细-辅助画像（1）',26,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_large_image1','详细-辅助扩大画像（1）',27,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_title2','详细-副标题（2）',28,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_comment2','详细-辅助评语（2）',29,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_image2','详细-辅助画像（2）',30,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_large_image2','详细-辅助扩大画像（2）',31,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_title3','详细-副标题（3）',32,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_comment3','详细-辅助评语（3）',33,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_image3','详细-辅助画像（3）',34,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_large_image3','详细-辅助扩大画像（3）',35,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_title4','详细-副标题（4）',36,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_comment4','详细-辅助评语（4）',37,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_image4','详细-辅助画像（4）',38,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_large_image4','详细-辅助扩大画像（4）',39,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_title5','详细-副标题（5）',40,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_comment5','详细-辅助评语（5）',41,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_image5','详细-辅助画像（5）',42,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'sub_large_image5','详细-辅助扩大画像（5）',43,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'deliv_date_id','发送日目标',44,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT recommend_product_id FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1) AS recommend_product_id1','推荐商品(1)',45,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT comment FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1) AS recommend_comment1','推荐评语(1)',46,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT recommend_product_id FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1 offset 1) AS recommend_product_id2','推荐商品(2)',47,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT comment FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1 offset 1) AS recommend_comment2','推荐评语(2)',48,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT recommend_product_id FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1 offset 2) AS recommend_product_id3','推荐商品(3)',49,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT comment FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1 offset 2) AS recommend_comment3','推荐评语(3)',50,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT recommend_product_id FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1 offset 3) AS recommend_product_id4','推荐商品(4)',51,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT comment FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1 offset 3) AS recommend_comment4','推荐评语(4)',52,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT recommend_product_id FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1 offset 4) AS recommend_product_id5','推荐商品(5)',53,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT comment FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1 offset 4) AS recommend_comment5','推荐评语(5)',54,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT recommend_product_id FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1 offset 5) AS recommend_product_id6','おすすめ商品(6)',55,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'(SELECT comment FROM dtb_recommend_products WHERE prdcls.product_id = dtb_recommend_products.product_id ORDER BY update_date DESC limit 1 offset 5) AS recommend_comment6','推荐评语(6)',56,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(1,'category_id','范畴ID',57,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'customer_id','顾客ID',1,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'name01','名1',2,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'name02','名2',3,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'kana01','名拼音1',4,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'kana02','名拼音2',5,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'zip01', '邮政编码1',6,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'zip02', '邮政编码2',7,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'pref', '省',8,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'addr01', '地址1',9,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'addr02', '地址2',10,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'email', '电子邮件',11,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'tel01', '电话号码1',12,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'tel02', '电话号码2',13,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'tel03', '电话号码3',14,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'fax01', '传真号码1',15,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'fax02', '传真号码2',16,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'fax03', '传真号码3',17,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'sex', '性别',18,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'job', '职业',19,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'birth', '誕生日',20,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'first_buy_date', '第一回购买日',21,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'last_buy_date', '最后购买日',22,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'buy_times', '购买回数',23,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'point', '点余额',24,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'note', '备考',25,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'create_date','登记日',26,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(2,'update_date','更新日',   27,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_id','定购ID',1,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'customer_id','顾客ID',2,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'message','要求等',3,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_name01','顾客名1',4,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_name02','顾客名2',5,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_kana01','顾客名拼音1',6,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_kana02','顾客名拼音2',7,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_email','邮件地址',8,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_tel01','电话号码1',9,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_tel02','电话号码2',10,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_tel03','电话号码3',11,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_fax01','传真号码1',12,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_fax02','传真号码2',13,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_fax03','传真号码3',14,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_zip01','邮政编码1',15,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_zip02','邮政编码2',16,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_pref','省',17,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_addr01','地址1',18,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_addr02','地址2',19,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_sex','性别',20,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_birth','出生年月日',21,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'order_job','职业种类',22,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_name01','发送处名',23,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_name02','发送处名',24,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_kana01','发送处名拼音',25,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_kana02','发送处名拼音',26,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_tel01','电话号码1',27,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_tel02','电话号码2',28,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_tel03','电话号码3',29,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_fax01','传真号码1',30,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_fax02','传真号码2',31,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_fax03','传真号码3',32,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_zip01','邮政编码1',33,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_zip02','邮政编码2',34,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_pref','省',35,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_addr01','地址1',36,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_addr02','地址2',37,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'subtotal','小计',38,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'discount','降价',39,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_fee','运费',40,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'charge','手续费',41,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'use_point','所用积分',42,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'add_point','增加积分',43,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'tax','税款',44,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'total','合计',45,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'payment_total','支付共计',46,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'payment_method','支付方式',47,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_time','发送时间',48,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'deliv_no','发送票据编号',49,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'note','店的笔记',50,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'status','对应状况',51,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'create_date','定购日期和时间',52,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(3,'update_date','更新日的时候',53,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_id','定购ID',1,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'campaign_id','运动ID',2,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'customer_id','顾客ID',3,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'message','要求等',4,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_name01','顾客名1',5,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_name02','顾客名2',6,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_kana01','顾客名拼音1',7,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_kana02','顾客名拼音2',8,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_email','邮件地址',9,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_tel01','电话号码1',10,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_tel02','电话号码2',11,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_tel03','电话号码3',12,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_fax01','传真号码1',13,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_fax02','传真号码2',14,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_fax03','传真号码3',15,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_zip01','邮政编码1',16,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_zip02','邮政编码2',17,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_pref','省',18,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_addr01','地址1',19,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_addr02','地址2',20,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_sex','性别',21,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_birth','出生年月日',22,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'order_job','职业种类',23,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_name01','发送处名',24,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_name02','发送处名',25,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_kana01','发送处名拼音',26,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_kana02','发送处名拼音',27,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_tel01','电话号码1',28,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_tel02','电话号码2',29,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_tel03','电话号码3',30,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_fax01','传真号码1',31,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_fax02','传真号码2',32,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_fax03','传真号码3',33,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_zip01','郵便番号1',34,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_zip02','郵便番号2',35,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_pref','省',36,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_addr01','地址1',37,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'deliv_addr02','地址2',38,now(),now());
insert into dtb_csv(csv_id,col,disp_name,rank,create_date,update_date)values(4,'payment_total','支付共计',39,now(),now());

INSERT INTO dtb_templates (template_code, template_name, create_date, update_date) VALUES('default','默认', now(), now());

insert into dtb_mailtemplate (template_id, subject, header, footer, creator_id, update_date, create_date) values (
1,
'定购谢谢。',
'这次承蒙定购实在谢谢。
下列定购内容没有搞错请确认。

',
'

==============================================================☆


这个消息因为是对顾客的通知专用承蒙作为对、
这个消息的回信发送问题也不能回答。
请谅解。

如果有问题水虿不明的点，从这边拜托。
http://

',0,Now(), now());

insert into dtb_news (news_date,rank, news_title, news_comment, creator_id, create_date, update_date)
values(now(),1,'网站开放了！','送交到家庭从单身生活以办公室等各种各样的景色支持 你的生活的商品！送交到家庭从单身生活以办公室等各种各样的景色支持 你的生活的商品！送交到家庭从单身生活以办公室等各种各样的景色支持 你的生活的商品！',1, now(), now());

INSERT INTO dtb_deliv (name,service_name,confirm_url,rank,status,del_flg,creator_id,create_date,update_date)
VALUES ('样品业者', '样品业者', '', 1, 1, 0, 2, now(), now());

INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 1);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 2);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 3);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 4);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 5);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 6);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 7);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 8);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 9);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 10);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 11);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 12);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 13);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 14);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 15);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 16);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 17);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 18);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 19);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 20);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 21);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 22);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 23);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 24);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 25);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 26);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 27);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 28);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 29);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 30);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 31);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 32);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 33);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 34);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 35);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 36);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 37);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 38);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 39);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 40);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 41);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 42);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 43);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 44);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 45);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 46);
INSERT INTO dtb_delivfee (deliv_id,fee,pref) VALUES (1, '1000', 47);

INSERT INTO dtb_delivtime (deliv_id, deliv_time) VALUES (1, '上午');
INSERT INTO dtb_delivtime (deliv_id, deliv_time) VALUES (1, '下午');

INSERT INTO dtb_payment (payment_method,charge,rule,deliv_id,rank,note,fix,status,del_flg,creator_id,create_date,update_date,payment_image,upper_rule) VALUES ('邮政转帐', 0, NULL, 1, 4, NULL, 2, 1, 0, 1, now(), now(), NULL, NULL);
INSERT INTO dtb_payment (payment_method,charge,rule,deliv_id,rank,note,fix,status,del_flg,creator_id,create_date,update_date,payment_image,upper_rule) VALUES ('现金挂号', 0, NULL, 1, 3, NULL, 2, 1, 0, 1, now(), now(), NULL, NULL);
INSERT INTO dtb_payment (payment_method,charge,rule,deliv_id,rank,note,fix,status,del_flg,creator_id,create_date,update_date,payment_image,upper_rule) VALUES ('银行汇款', 0, NULL, 1, 2, NULL, 2, 1, 0, 1, now(), now(), NULL, NULL);
INSERT INTO dtb_payment (payment_method,charge,rule,deliv_id,rank,note,fix,status,del_flg,creator_id,create_date,update_date,payment_image,upper_rule) VALUES ('交货付款', 0, NULL, 1, 1, NULL, 2, 1, 0, 1, now(), now(), NULL, NULL);

INSERT INTO dtb_products (name,deliv_fee,sale_limit,sale_unlimited,category_id,rank,status,product_flag,point_rate,comment1,comment2,comment3,comment4,comment5,comment6,file1,file2,file3,file4,file5,file6,main_list_comment,main_list_image,main_comment,main_image,main_large_image,sub_title1,sub_comment1,sub_image1,sub_large_image1,sub_title2,sub_comment2,sub_image2,sub_large_image2,sub_title3,sub_comment3,sub_image3,sub_large_image3,sub_title4,sub_comment4,sub_image4,sub_large_image4,sub_title5,sub_comment5,sub_image5,sub_large_image5,sub_title6,sub_comment6,sub_image6,sub_large_image6,del_flg,creator_id,create_date,update_date,deliv_date_id)
VALUES ('冰激凌', NULL, NULL, NULL, 5, 1, 1, '10010', 10, NULL, NULL, '冰,香子兰,巧克力,抹茶', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '暑い夏にどうぞ。', '08311201_44f65122ee5fe.jpg', '冷たいものはいかがですか？', '08311202_44f6515906a41.jpg', '08311203_44f651959bcb5.jpg', NULL, '<b>おいしいよ<b>', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 2, now(), now(), 2);
INSERT INTO dtb_products (name,deliv_fee,sale_limit,sale_unlimited,category_id,rank,status,product_flag,point_rate,comment1,comment2,comment3,comment4,comment5,comment6,file1,file2,file3,file4,file5,file6,main_list_comment,main_list_image,main_comment,main_image,main_large_image,sub_title1,sub_comment1,sub_image1,sub_large_image1,sub_title2,sub_comment2,sub_image2,sub_large_image2,sub_title3,sub_comment3,sub_image3,sub_large_image3,sub_title4,sub_comment4,sub_image4,sub_large_image4,sub_title5,sub_comment5,sub_image5,sub_large_image5,sub_title6,sub_comment6,sub_image6,sub_large_image6,del_flg,creator_id,create_date,update_date,deliv_date_id)
VALUES ('锅', NULL, 5, NULL, NULL, 1, 1, '11001', 5, NULL, NULL, '锅', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '一人用からあります。', '08311311_44f661811fec0.jpg', 'たまには鍋でもどうでしょう。', '08311313_44f661dc649fb.jpg', '08311313_44f661e5698a6.jpg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, 2, now(), now(), 3);

INSERT INTO dtb_products_class (product_id,classcategory_id1,classcategory_id2,product_code,stock,stock_unlimited,sale_limit,price01,price02,status,creator_id,create_date,update_date)
VALUES (1, 3, 6, 'ice-01', NULL, 1, NULL, 150, 120, NULL, 2, now(), now());
DELETE FROM dtb_products_class;
INSERT INTO dtb_products_class (product_id,classcategory_id1,classcategory_id2,product_code,stock,stock_unlimited,sale_limit,price01,price02,status,creator_id,create_date,update_date)
VALUES (1, 3, 6, 'ice-01', NULL, 1, NULL, 150, 120, NULL, 2, now(), now());
INSERT INTO dtb_products_class (product_id,classcategory_id1,classcategory_id2,product_code,stock,stock_unlimited,sale_limit,price01,price02,status,creator_id,create_date,update_date)
VALUES (1, 3, 5, 'ice-01', NULL, 1, NULL, 150, 120, NULL, 2, now(), now());
INSERT INTO dtb_products_class (product_id,classcategory_id1,classcategory_id2,product_code,stock,stock_unlimited,sale_limit,price01,price02,status,creator_id,create_date,update_date)
VALUES (1, 3, 4, 'ice-01', NULL, 1, NULL, 150, 120, NULL, 2, now(), now());
INSERT INTO dtb_products_class (product_id,classcategory_id1,classcategory_id2,product_code,stock,stock_unlimited,sale_limit,price01,price02,status,creator_id,create_date,update_date)
VALUES (1, 2, 6, 'ice-01', NULL, 1, NULL, 150, 120, NULL, 2, now(), now());
INSERT INTO dtb_products_class (product_id,classcategory_id1,classcategory_id2,product_code,stock,stock_unlimited,sale_limit,price01,price02,status,creator_id,create_date,update_date)
VALUES (1, 2, 5, 'ice-01', NULL, 1, NULL, 150, 120, NULL, 2, now(), now());
INSERT INTO dtb_products_class (product_id,classcategory_id1,classcategory_id2,product_code,stock,stock_unlimited,sale_limit,price01,price02,status,creator_id,create_date,update_date)
VALUES (1, 2, 4, 'ice-01', NULL, 1, NULL, 150, 120, NULL, 2, now(), now());
INSERT INTO dtb_products_class (product_id,classcategory_id1,classcategory_id2,product_code,stock,stock_unlimited,sale_limit,price01,price02,status,creator_id,create_date,update_date)
VALUES (1, 1, 6, 'ice-01', NULL, 1, NULL, 150, 120, NULL, 2, now(), now());
INSERT INTO dtb_products_class (product_id,classcategory_id1,classcategory_id2,product_code,stock,stock_unlimited,sale_limit,price01,price02,status,creator_id,create_date,update_date)
VALUES (1, 1, 5, 'ice-01', NULL, 1, NULL, 150, 120, NULL, 2, now(), now());
INSERT INTO dtb_products_class (product_id,classcategory_id1,classcategory_id2,product_code,stock,stock_unlimited,sale_limit,price01,price02,status,creator_id,create_date,update_date)
VALUES (1, 1, 4, 'ice-01', NULL, 1, NULL, 150, 120, NULL, 2, now(), now());
INSERT INTO dtb_products_class (product_id,classcategory_id1,classcategory_id2,product_code,stock,stock_unlimited,sale_limit,price01,price02,status,creator_id,create_date,update_date)
VALUES (2, 0, 0, 'nabe-01', 100, NULL, NULL, 1700, 1650, NULL, 2, now(), now());

INSERT INTO dtb_recommend_products (product_id, recommend_product_id, rank,comment,status,creator_id,create_date,update_date) VALUES (2, 1, 4, '换口味。', 0, 2, now(), now());

INSERT INTO dtb_class (name,status,rank,creator_id,create_date,update_date,del_flg,product_id) VALUES ('味', NULL, 1, 2, now(), now(), 0, NULL);
INSERT INTO dtb_class (name,status,rank,creator_id,create_date,update_date,del_flg,product_id) VALUES ('大小', NULL, 2, 2, now(), now(), 0, NULL);

INSERT INTO dtb_classcategory (name,class_id,status,rank,creator_id,create_date,update_date,del_flg) VALUES ('香子兰', 1, NULL, 1, 2, now(), now(), 0);
INSERT INTO dtb_classcategory (name,class_id,status,rank,creator_id,create_date,update_date,del_flg) VALUES ('巧克力', 1, NULL, 2, 2, now(), now(), 0);
INSERT INTO dtb_classcategory (name,class_id,status,rank,creator_id,create_date,update_date,del_flg) VALUES ('抹茶', 1, NULL, 3, 2, now(), now(), 0);
INSERT INTO dtb_classcategory (name,class_id,status,rank,creator_id,create_date,update_date,del_flg) VALUES ('L', 2, NULL, 1, 2, now(), now(), 0);
INSERT INTO dtb_classcategory (name,class_id,status,rank,creator_id,create_date,update_date,del_flg) VALUES ('M', 2, NULL, 2, 2, now(), now(), 0);
INSERT INTO dtb_classcategory (name,class_id,status,rank,creator_id,create_date,update_date,del_flg) VALUES ('S', 2, NULL, 3, 2, now(), now(), 0);

INSERT INTO dtb_classcategory (classcategory_id, class_id, rank, creator_id, create_date, update_date)
VALUES (0, 0, 0, 0, now(), now());
UPDATE dtb_classcategory SET classcategory_id = 0 WHERE class_id = 0;

INSERT INTO dtb_category (category_name,parent_category_id,level,rank,creator_id,create_date,update_date,del_flg) VALUES ('食品', 0, 1, 4, 2, now(), now(), 0);
INSERT INTO dtb_category (category_name,parent_category_id,level,rank,creator_id,create_date,update_date,del_flg) VALUES ('杂货', 0, 1, 5, 2, now(), now(), 0);
INSERT INTO dtb_category (category_name,parent_category_id,level,rank,creator_id,create_date,update_date,del_flg) VALUES ('点心', 1, 2, 2, 2, now(), now(), 0);
INSERT INTO dtb_category (category_name,parent_category_id,level,rank,creator_id,create_date,update_date,del_flg) VALUES ('锅', 1, 2, 3, 2, now(), now(), 0);
INSERT INTO dtb_category (category_name,parent_category_id,level,rank,creator_id,create_date,update_date,del_flg) VALUES ('冰激凌', 3, 3, 1, 2, now(), now(), 0);

INSERT INTO dtb_product_categories (product_id,category_id,rank) VALUES (1,5,1);
INSERT INTO dtb_product_categories (product_id,category_id,rank) VALUES (2,4,2);

INSERT INTO dtb_category_count VALUES (4, 1, now());
INSERT INTO dtb_category_count VALUES (5, 1, now());

INSERT INTO dtb_category_total_count VALUES (3, 1, now());
INSERT INTO dtb_category_total_count VALUES (1, 2, now());
INSERT INTO dtb_category_total_count VALUES (2, NULL, now());
INSERT INTO dtb_category_total_count VALUES (5, 1, now());
INSERT INTO dtb_category_total_count VALUES (4, 1, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第1条(会员)','1.把遵从本公司制定的手续为本规章进行同意之后,入会的申请的个人称为所谓「会员」。\n2.会员把有关有关本公司明确指示了的会员的属性的信息及会员的交易的履历等的信息称为所谓「会员信息」。\n3.个规章,是被全部的会员适用,登记手续时及在登记后护符领受的规章。\n',12,0,Now(),0, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第2条(登记)','1.被会员资格本规章做了同意之后,所定的入会申请的顾客,在所定的登记手续完成后有作为会员的资格。会员登记手续,请会员和变成的本人去。由于代理的登记全部不能承认。再者,判断了过去会员资格被取消了和其他本公司不适合来自的会员申请有如果拒绝。\n2.请会员信息的输入会员登记手续时候,很好地念,所定的输入形式正确输入输入上的注意必要事项。在会员信息的登记中,特殊记号·旧汉字·罗马数字等不习惯使用。如果这些的文字被登记了本公司变更。\n3. 口令的管理\n (1)口令作为只会员本人能利用的东西,第三者作为不能转让·借与的东西。\n (2)口令,没有别人被知道的事的那样定期性地变更等,会员本人请有责任管理。\n (3)用口令对本公司被进行了的意见表示,与会员本人的意见表示看作,为此产生的支付等全部成为会员的责任。\n',11,0,Now(),0, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第3条(变更)','1.会员,如果对姓名,地址等本公司申报了的事项有变更,作为很快地与本公司联系的东西。\n2.关于根据不被做的事产生了变更登记的损失,本公司全部不承担责任。同时,如果变更登记被做了,在变更登记前也已经手续被做了的交易,因为按照变更登记前的信息被进行请注意。\n',10,0,Now(),0, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第4条(退会)','如果会员希望退会,会员本人请进行退会手续。到所定的退会手续的结束后,退会。\n',9,0,Now(),0, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第5条(会员资格的丧失及赔偿义务)','1.有会员,会员资格取得申请时候做了虚报的时候,疏怠了由于邮购的货款支付债务的时候,其他本公司作为会员承认不适当的理由的时候,本公司,能取消会员资格决定。\n2.会员,做了决定为以下的各号的行为的时候,承担赔偿根据这个本公司蒙受了的损失的责任。\n (1)会员号码,做做侵害不正当利用口令的事\n (2)正当主页访问窜改信息,发送对这个主页有害的电脑程序等做,妨碍本公司的营业的事\n (3)本公司处理的商品的知识产权的行为的事\n (4)其他,违反这个利用规章的行为的事\n',8,0,Now(),0, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第6条(会员信息的对待)','1.本公司,作为原则会员的事前的有没有同意地对第三者明确指示没会员信息。但,是下面的各号的情况,作为会员的事前的没有同意地,本公司能明确指示会员信息及其他的顾客信息的东西。\n (1)如果本公司判断了为了保护按照法令被要求明确指示\n (2)本公司的权利,利益,名誉等必要为\n2.会员信息附有,本公司的随着「对个人信息保护的取组看」,本公司管理。本公司,把会员信息,作为为了图谋给会员的服务提供,服务内容的提高,服务的利用促进,和服务的健全且圆滑的营运的确保的目的,能本公司放置利用的东西。\n3.本公司,对会员,作为能由于邮件杂志及其他的方法的进行含信息提供(广告)的东西。会员不希望信息提供的情况,如果遵从本公司所定的方法,可以通知那个意思,停止信息提供。但,对本服务营运必要的信息提供附有,不能根据会员的希望做停止。\n',7,0,Now(),0, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第7条(禁止事项)','禁止在本服务的利用时,对会员进行下面的各号的行为的事。在本服务的利用时,禁止对会员进行下面的各号的行为的事。\n 1.法令又本规章,本服务利用上的注意,违反在本服务的买东西上的注意及其他的本规章等的事\n 2.本公司,和其他的第三者的权利,利益,伤害名誉等的事\n 3.有给青少年的身心带来坏影响的可能的行为,其他进行违犯公共秩序良好的风俗的行为的事\n 4.进行成为其他的利用者及其他的第三者麻烦的行为和使之抱不舒服的行为的事\n 5.输入虚伪的信息的事\n 6.有害的电脑程序,发送再写入邮件等的事\n 7.不正当访问本公司的服务器及其他的计算机的事\n 8.第三者借与·转让口令的事,或与第三者共同使用的事\n 9.其他本公司判断不合适的事)\n',6,0,Now(),0, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第8条(服务的中断·停止等)','1.本公司,为了保持本服务的稼动状态良好,如果符合下面的各号的一,没有预告,本服务的提供全部某在就有停止一部。\n (1)如果根据为了系统的定期保守及紧急保守的必要的情况\n (2)系统负荷集中了的\n (3)火灾,停电,由于第三者的干扰行为等系统的运用困难了\n (4)其他,如果停的wo不得系统的停止必要和本公司判断了\n',5,0,Now(),0, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第9条(服务的变更·废止)','本公司,根据那个判断服务的全部再把一部作为事前的没有通知地,适宜地能变更·废止的东西。\n',4,0,Now(),0, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第10条(免除责任)','1.由于通信线路和计算机等的障碍的系统的中断·迟缓·中止·数据的消失,关于有关根据对数据的不正当访问产生了的损失,其他本公司的服务对会员产生了的损失,本公司作为全部不承担责任的东西。\n2.本公司,不保证从本公司的网页·服务器·域等被发送的邮件·内容中,没包含电脑病毒等的有害的东西的事。\n3.关于根据会员违反了本规章等的事产生了的损失,本公司全部不承担责任。\n',3,0,Now(),0, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第11条(本规章的修改)','能定(说补充,同时作为本公司,把本规章做为任意能修改的东西,在本公司中本规章的规章以下「补充规章」)。本规章的修改再补充,修改后的本规章再把补充规章作为本公司所定的网站揭示了的时候上产生那个效力的东西。这个情况,会员,与遵从修改后的规章及补充规章的东西做。\n',2,0,Now(),0, now());

INSERT INTO dtb_kiyaku (kiyaku_title, kiyaku_text, rank, creator_id, update_date, del_flg, create_date)
VALUES ('第12条(依据法,管辖法院)','如果把有关本规章产生了纠纷的,管辖本公司总店所在地的地方法院作为第一审的专属的同意管辖法院。\n',1,0,Now(),0, now());

INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('1', '安徽省', '1');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('2', '福建省', '2');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('3', '甘肃省', '3');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('4', '广东省', '4');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('5', '贵州省', '5');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('6', '海南省', '6');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('7', '河北省', '7');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('8', '黑龙江省', '8');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('9', '河南省', '9');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('10', '湖北省', '10');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('11', '湖南省', '11');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('12', '江苏省', '12');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('13', '江西省', '13');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('14', '吉林省', '14');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('15', '辽宁省', '15');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('16', '青海省', '16');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('17', '陕西省', '17');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('18', '山东省', '18');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('19', '山西省', '19');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('20', '四川省', '20');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('21', '云南省', '21');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('22', '浙江省', '22');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('23', '广西壮族自治区', '23');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('24', '宁夏天回族自治区', '24');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('25', '内蒙古自治区', '25');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('26', '新疆维吾尔自治区', '26');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('27', '西藏自治区', '27');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('28', '北京市', '28');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('29', '重庆市', '29');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('30', '上海市', '30');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('31', '天津市', '31');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('32', '澳门特別行政区', '32');
INSERT INTO mtb_pref (pref_id, pref_name, rank) VALUES ('33', '香港特別行政区', '33');
INSERT INTO mtb_permission VALUES ('/admin/system/index.php', '0',0);
INSERT INTO mtb_permission VALUES ('/admin/system/delete.php', '0',1);
INSERT INTO mtb_permission VALUES ('/admin/system/input.php', '0',2);
INSERT INTO mtb_permission VALUES ('/admin/system/master.php', '0',3);
INSERT INTO mtb_permission VALUES ('/admin/system/master_delete.php', '0',4);
INSERT INTO mtb_permission VALUES ('/admin/system/master_rank.php', '0',5);
INSERT INTO mtb_permission VALUES ('/admin/system/mastercsv.php', '0',6);
INSERT INTO mtb_permission VALUES ('/admin/system/rank.php', '0',7);
INSERT INTO mtb_permission VALUES ('/admin/entry/index.php', '1',8);
INSERT INTO mtb_permission VALUES ('/admin/entry/delete.php', '1',9);
INSERT INTO mtb_permission VALUES ('/admin/entry/inputzip.php', '1',10);
INSERT INTO mtb_permission VALUES ('/admin/search/delete_note.php', '1',11);
INSERT INTO mtb_disable_logout VALUES ('1', '/shopping/deliv.php',0);
INSERT INTO mtb_disable_logout VALUES ('2', '/shopping/payment.php',1);
INSERT INTO mtb_disable_logout VALUES ('3', '/shopping/confirm.php',2);
INSERT INTO mtb_disable_logout VALUES ('4', '/shopping/card.php',3);
INSERT INTO mtb_disable_logout VALUES ('5', '/shopping/loan.php',4);
INSERT INTO mtb_authority VALUES ('0', '管理者',0);
INSERT INTO mtb_work VALUES ('0', '非劳动',0);
INSERT INTO mtb_work VALUES ('1', '劳动',1);
INSERT INTO mtb_disp VALUES ('1', '公开',0);
INSERT INTO mtb_disp VALUES ('2', '非公开',1);
INSERT INTO mtb_class VALUES ('1', '没有规格',0);
INSERT INTO mtb_class VALUES ('2', '规格有',1);
INSERT INTO mtb_srank VALUES ('1', '1',0);
INSERT INTO mtb_srank VALUES ('2', '2',1);
INSERT INTO mtb_srank VALUES ('3', '3',2);
INSERT INTO mtb_srank VALUES ('4', '4',3);
INSERT INTO mtb_srank VALUES ('5', '5',4);
INSERT INTO mtb_status VALUES ('1', 'NEW',0);
INSERT INTO mtb_status VALUES ('2', '留下仅仅',1);
INSERT INTO mtb_status VALUES ('3', '点2倍',2);
INSERT INTO mtb_status VALUES ('4', '推荐',3);
INSERT INTO mtb_status VALUES ('5', '限制品',4);
INSERT INTO mtb_status_image VALUES ('1', 'img/right_product/icon01.gif',0);
INSERT INTO mtb_status_image VALUES ('2', 'img/right_product/icon02.gif',1);
INSERT INTO mtb_status_image VALUES ('3', 'img/right_product/icon03.gif',2);
INSERT INTO mtb_status_image VALUES ('4', 'img/right_product/icon04.gif',3);
INSERT INTO mtb_status_image VALUES ('5', 'img/right_product/icon05.gif',4);
INSERT INTO mtb_allowed_tag VALUES ('0', 'table',0);
INSERT INTO mtb_allowed_tag VALUES ('1', 'tr',1);
INSERT INTO mtb_allowed_tag VALUES ('2', 'td',2);
INSERT INTO mtb_allowed_tag VALUES ('3', 'a',3);
INSERT INTO mtb_allowed_tag VALUES ('4', 'b',4);
INSERT INTO mtb_allowed_tag VALUES ('5', 'blink',5);
INSERT INTO mtb_allowed_tag VALUES ('6', 'br',6);
INSERT INTO mtb_allowed_tag VALUES ('7', 'center',7);
INSERT INTO mtb_allowed_tag VALUES ('8', 'font',8);
INSERT INTO mtb_allowed_tag VALUES ('9', 'h',9);
INSERT INTO mtb_allowed_tag VALUES ('10', 'hr',10);
INSERT INTO mtb_allowed_tag VALUES ('11', 'img',11);
INSERT INTO mtb_allowed_tag VALUES ('12', 'li',12);
INSERT INTO mtb_allowed_tag VALUES ('13', 'strong',13);
INSERT INTO mtb_allowed_tag VALUES ('14', 'p',14);
INSERT INTO mtb_allowed_tag VALUES ('15', 'div',15);
INSERT INTO mtb_allowed_tag VALUES ('16', 'i',16);
INSERT INTO mtb_allowed_tag VALUES ('17', 'u',17);
INSERT INTO mtb_allowed_tag VALUES ('18', 's',18);
INSERT INTO mtb_allowed_tag VALUES ('19', '/table',19);
INSERT INTO mtb_allowed_tag VALUES ('20', '/tr',20);
INSERT INTO mtb_allowed_tag VALUES ('21', '/td',21);
INSERT INTO mtb_allowed_tag VALUES ('22', '/a',22);
INSERT INTO mtb_allowed_tag VALUES ('23', '/b',23);
INSERT INTO mtb_allowed_tag VALUES ('24', '/blink',24);
INSERT INTO mtb_allowed_tag VALUES ('25', '/br',25);
INSERT INTO mtb_allowed_tag VALUES ('26', '/center',26);
INSERT INTO mtb_allowed_tag VALUES ('27', '/font',27);
INSERT INTO mtb_allowed_tag VALUES ('28', '/h',28);
INSERT INTO mtb_allowed_tag VALUES ('29', '/hr',29);
INSERT INTO mtb_allowed_tag VALUES ('30', '/img',30);
INSERT INTO mtb_allowed_tag VALUES ('31', '/li',31);
INSERT INTO mtb_allowed_tag VALUES ('32', '/strong',32);
INSERT INTO mtb_allowed_tag VALUES ('33', '/p',33);
INSERT INTO mtb_allowed_tag VALUES ('34', '/div',34);
INSERT INTO mtb_allowed_tag VALUES ('35', '/i',35);
INSERT INTO mtb_allowed_tag VALUES ('36', '/u',36);
INSERT INTO mtb_allowed_tag VALUES ('37', '/s',37);
INSERT INTO mtb_page_max VALUES ('10', '10',0);
INSERT INTO mtb_page_max VALUES ('20', '20',1);
INSERT INTO mtb_page_max VALUES ('30', '30',2);
INSERT INTO mtb_page_max VALUES ('40', '40',3);
INSERT INTO mtb_page_max VALUES ('50', '50',4);
INSERT INTO mtb_page_max VALUES ('60', '60',5);
INSERT INTO mtb_page_max VALUES ('70', '70',6);
INSERT INTO mtb_page_max VALUES ('80', '80',7);
INSERT INTO mtb_page_max VALUES ('90', '90',8);
INSERT INTO mtb_page_max VALUES ('100', '100',9);
INSERT INTO mtb_magazine_type VALUES ('1', 'HTML',0);
INSERT INTO mtb_magazine_type VALUES ('2', '文本',1);
INSERT INTO mtb_magazine_type VALUES ('3', 'HTML模板',2);
INSERT INTO mtb_mail_magazine_type VALUES ('1', 'HTML邮件',0);
INSERT INTO mtb_mail_magazine_type VALUES ('2', '文本邮件',1);
INSERT INTO mtb_mail_magazine_type VALUES ('3', '不希望',2);
INSERT INTO mtb_recommend VALUES ('5', '★★★★★',0);
INSERT INTO mtb_recommend VALUES ('4', '★★★★',1);
INSERT INTO mtb_recommend VALUES ('3', '★★★',2);
INSERT INTO mtb_recommend VALUES ('2', '★★',3);
INSERT INTO mtb_recommend VALUES ('1', '★',4);
INSERT INTO mtb_taxrule VALUES ('1', '四舍五入',0);
INSERT INTO mtb_taxrule VALUES ('2', '切掉',1);
INSERT INTO mtb_taxrule VALUES ('3', '结束',2);
INSERT INTO mtb_mail_template VALUES ('1', '定购接待邮件',0);
INSERT INTO mtb_mail_template VALUES ('2', '定购废除接待邮件',1);
INSERT INTO mtb_mail_template VALUES ('3', '寄送确认邮件',2);
INSERT INTO mtb_mail_tpl_path VALUES ('1', 'mail_templates/order_mail.tpl',0);
INSERT INTO mtb_mail_tpl_path VALUES ('2', 'mail_templates/order_mail.tpl',1);
INSERT INTO mtb_mail_tpl_path VALUES ('3', 'mail_templates/order_mail.tpl',2);
INSERT INTO mtb_mail_tpl_path VALUES ('4', 'mail_templates/contact_mail.tpl',3);
INSERT INTO mtb_job VALUES ('1', '公务员',0);
INSERT INTO mtb_job VALUES ('2', '顾问',1);
INSERT INTO mtb_job VALUES ('3', '计算机关联技术工作',2);
INSERT INTO mtb_job VALUES ('4', '计算机关联以外的技术工作',3);
INSERT INTO mtb_job VALUES ('5', '金融关系',4);
INSERT INTO mtb_job VALUES ('6', '医生',5);
INSERT INTO mtb_job VALUES ('7', '律师',6);
INSERT INTO mtb_job VALUES ('8', '总务·人事·事务',7);
INSERT INTO mtb_job VALUES ('9', '营业·销售',8);
INSERT INTO mtb_job VALUES ('10', '研究·开发',9);
INSERT INTO mtb_job VALUES ('11', '宣传·宣传',10);
INSERT INTO mtb_job VALUES ('12', '规划·营销',11);
INSERT INTO mtb_job VALUES ('13', '设计关系',12);
INSERT INTO mtb_job VALUES ('14', '公司经营·干事',13);
INSERT INTO mtb_job VALUES ('15', '出版·宣传媒体关系',14);
INSERT INTO mtb_job VALUES ('16', '学生·无固定职业者',15);
INSERT INTO mtb_job VALUES ('17', '主妇',16);
INSERT INTO mtb_job VALUES ('18', '其他',17);
INSERT INTO mtb_reminder VALUES ('1', '母亲的旧姓呢？',0);
INSERT INTO mtb_reminder VALUES ('2', '喜爱的漫画呢？',1);
INSERT INTO mtb_reminder VALUES ('3', '非常喜欢的宠物的名字呢？',2);
INSERT INTO mtb_reminder VALUES ('4', '初恋的人的名字呢？',3);
INSERT INTO mtb_reminder VALUES ('5', '有趣的电影呢？',4);
INSERT INTO mtb_reminder VALUES ('6', '尊敬的老师的名字呢？',5);
INSERT INTO mtb_reminder VALUES ('7', '喜欢的食物呢？',6);
INSERT INTO mtb_sex VALUES ('1', '男性',0);
INSERT INTO mtb_sex VALUES ('2', '女性',1);
INSERT INTO mtb_mail_type VALUES ('1', '个人电脑用地址',0);
INSERT INTO mtb_mail_type VALUES ('2', '手机用地址',1);
INSERT INTO mtb_page_rows VALUES ('10', '10',0);
INSERT INTO mtb_page_rows VALUES ('20', '20',1);
INSERT INTO mtb_page_rows VALUES ('30', '30',2);
INSERT INTO mtb_page_rows VALUES ('40', '40',3);
INSERT INTO mtb_page_rows VALUES ('50', '50',4);
INSERT INTO mtb_page_rows VALUES ('60', '60',5);
INSERT INTO mtb_page_rows VALUES ('70', '70',6);
INSERT INTO mtb_page_rows VALUES ('80', '80',7);
INSERT INTO mtb_page_rows VALUES ('90', '90',8);
INSERT INTO mtb_page_rows VALUES ('100', '100',9);
INSERT INTO mtb_order_status VALUES ('1', '新规章接待',0);
INSERT INTO mtb_order_status VALUES ('2', '入款等候',1);
INSERT INTO mtb_order_status VALUES ('6', '入款完毕',2);
INSERT INTO mtb_order_status VALUES ('3', '废除',3);
INSERT INTO mtb_order_status VALUES ('4', '寄送中',4);
INSERT INTO mtb_order_status VALUES ('5', '发送完毕',5);
INSERT INTO mtb_order_status_color VALUES ('1', '#FFFFFF',0);
INSERT INTO mtb_order_status_color VALUES ('2', '#FFDE9B',1);
INSERT INTO mtb_order_status_color VALUES ('3', '#C9C9C9',2);
INSERT INTO mtb_order_status_color VALUES ('4', '#FFD9D9',3);
INSERT INTO mtb_order_status_color VALUES ('5', '#BFDFFF',4);
INSERT INTO mtb_order_status_color VALUES ('6', '#FFFFAB',5);
INSERT INTO mtb_product_status_color VALUES ('1','#FFFFFF', 0);
INSERT INTO mtb_product_status_color VALUES ('2', '#C9C9C9', 1);
INSERT INTO mtb_product_status_color VALUES ('3', '#DDE6F2', 2);
INSERT INTO mtb_wday VALUES ('0', '日',0);
INSERT INTO mtb_wday VALUES ('1', '月',1);
INSERT INTO mtb_wday VALUES ('2', '火',2);
INSERT INTO mtb_wday VALUES ('3', '水',3);
INSERT INTO mtb_wday VALUES ('4', '木',4);
INSERT INTO mtb_wday VALUES ('5', '金',5);
INSERT INTO mtb_wday VALUES ('6', '土',6);
INSERT INTO mtb_delivery_date VALUES ('1', '即日',0);
INSERT INTO mtb_delivery_date VALUES ('2', '1〜2日后',1);
INSERT INTO mtb_delivery_date VALUES ('3', '3〜4日后',2);
INSERT INTO mtb_delivery_date VALUES ('4', '1周以后',3);
INSERT INTO mtb_delivery_date VALUES ('5', '2周以后',4);
INSERT INTO mtb_delivery_date VALUES ('6', '3周以后',5);
INSERT INTO mtb_delivery_date VALUES ('7', '1个月以后',6);
INSERT INTO mtb_delivery_date VALUES ('8', '2个月以后',7);
INSERT INTO mtb_delivery_date VALUES ('9', '寄送(商品到货后)',8);
INSERT INTO mtb_product_list_max VALUES ('15', '15件',0);
INSERT INTO mtb_product_list_max VALUES ('30', '30件',1);
INSERT INTO mtb_product_list_max VALUES ('50', '50件',2);
INSERT INTO mtb_convenience VALUES ('1', 'Seven-Eleven',0);
INSERT INTO mtb_convenience VALUES ('2', '全家便利店',1);
INSERT INTO mtb_convenience VALUES ('3', '小组KSUNX',2);
INSERT INTO mtb_convenience VALUES ('4', '罗森·精工mart',3);
INSERT INTO mtb_convenience VALUES ('5', 'Ministop·daily山崎·山崎daily店',4);
INSERT INTO mtb_conveni_message VALUES ('1', '从上述URL印刷，或汇款票在纸上记录汇款票号码，全国的Seven-Eleven请支付。',0);
INSERT INTO mtb_conveni_message VALUES ('2', '公司代码，在纸等上记录接待号码，请给(对)全国的全家便利店支付。',1);
INSERT INTO mtb_conveni_message VALUES ('3', '上述URL印刷，或汇款票在纸等上记录手机结算号码，全国的小组KSUNX请支付。',2);
INSERT INTO mtb_conveni_message VALUES ('4', '在纸上记录汇款票号码，全国的罗森再精工mart请支付。',3);
INSERT INTO mtb_conveni_message VALUES ('5', '从上述URL印刷(印制)汇款票，全国的Ministop·daily山崎·山崎daily店请支付',4);
INSERT INTO mtb_db VALUES ('1', 'PostgreSQL',0);
INSERT INTO mtb_db VALUES ('2', 'MySQL',1);
INSERT INTO mtb_target VALUES ('1', 'LeftNavi',0);
INSERT INTO mtb_target VALUES ('2', 'MainHead',1);
INSERT INTO mtb_target VALUES ('3', 'RightNavi',2);
INSERT INTO mtb_target VALUES ('4', 'MainFoot',3);
INSERT INTO mtb_target VALUES ('5', 'Unused',4);
INSERT INTO mtb_review_deny_url VALUES ('0', 'http://',0);
INSERT INTO mtb_review_deny_url VALUES ('1', 'https://',1);
INSERT INTO mtb_review_deny_url VALUES ('2', 'ttp://',2);
INSERT INTO mtb_review_deny_url VALUES ('3', 'ttps://',3);
INSERT INTO mtb_track_back_status VALUES ('1', '表示',0);
INSERT INTO mtb_track_back_status VALUES ('2', '非表示',1);
INSERT INTO mtb_track_back_status VALUES ('3', '垃圾邮件',2);
INSERT INTO mtb_site_control_track_back VALUES ('1', '有效',0);
INSERT INTO mtb_site_control_track_back VALUES ('2', '无效',1);
INSERT INTO mtb_site_control_affiliate VALUES ('1', '有效',0);
INSERT INTO mtb_site_control_affiliate VALUES ('2', '无效',1);
INSERT INTO mtb_mobile_domain VALUES (1, 'docomo.ne.jp', 0);
INSERT INTO mtb_mobile_domain VALUES (2, 'ezweb.ne.jp', 1);
INSERT INTO mtb_mobile_domain VALUES (3, 'softbank.ne.jp', 2);
INSERT INTO mtb_mobile_domain VALUES (4, 'vodafone.ne.jp', 3);
INSERT INTO mtb_mobile_domain VALUES (5, 'pdx.ne.jp', 4);
INSERT INTO mtb_ownersstore_err VALUES ('1000', '不明的错误发生了。', 0);
INSERT INTO mtb_ownersstore_err VALUES ('1001', '不正当的参数被发送了。', 1);
INSERT INTO mtb_ownersstore_err VALUES ('1002', '认证失败了。<br />·临时会员，请进行本会员登记。<br />·认证钥匙是不是确实被设定请确认。', 2);
INSERT INTO mtb_ownersstore_err VALUES ('1003', '认证失败了。<br />·临时会员，请进行本会员登记。<br />·认证钥匙是不是确实被设定请确认。', 3);
INSERT INTO mtb_ownersstore_err VALUES ('1004', '没有购买完毕的商品。', 4);
INSERT INTO mtb_ownersstore_err VALUES ('1005', '没有下载可能的提高数据有。<br />·社会地位「入款等候的」可能性的已经有被。<br />·安装的组件最新版的可能性。', 5);
INSERT INTO mtb_ownersstore_err VALUES ('1006', '用送信服务器错误发生了。', 6);
INSERT INTO mtb_ownersstore_err VALUES ('1007', '下载完成通知失败了。', 7);
INSERT INTO mtb_ownersstore_err VALUES ('2001', '管理画面的认证失败了。<br />管理画面首页，请进入。', 8);
INSERT INTO mtb_ownersstore_err VALUES ('2002', '不能连接向送信服务器。', 9);
INSERT INTO mtb_ownersstore_err VALUES ('2003', '不能连接向送信服务器。', 10);
INSERT INTO mtb_ownersstore_err VALUES ('2004', '用送信服务器错误发生了。', 11);
INSERT INTO mtb_ownersstore_err VALUES ('2005', '认证钥匙没被设定。<br />·「认证钥匙设定」设定认证钥匙。', 12);
INSERT INTO mtb_ownersstore_err VALUES ('2006', '是不正当的访问。', 13);
INSERT INTO mtb_ownersstore_err VALUES ('2007', '不正当的参数被发送了。', 14);
INSERT INTO mtb_ownersstore_err VALUES ('2008', '自动更新无效。', 15);
INSERT INTO mtb_ownersstore_err VALUES ('2009', '文件的写入失败了。<br />·写入权限确实没被设定。<br />·data/downloads/tmp目录里(上)写入是不是有权限请确认', 16);
INSERT INTO mtb_ownersstore_err VALUES ('2010', '文件的写入失败了。<br />·「对数(记录)管理」确认详细。', 17);
INSERT INTO mtb_ownersstore_ips VALUES (0, '210.188.195.143', 0);
INSERT INTO mtb_constants VALUES ('SAMPLE_ADDRESS1','"市区镇村名（例：北京市东城区金宝街）"',1,'服务台表示关联');
INSERT INTO mtb_constants VALUES ('SAMPLE_ADDRESS2','"番地(门牌)·大楼名（例：11号）"',2,'服务台表示关联');
INSERT INTO mtb_constants VALUES ('USER_DIR','"user_data/"',3,'用户文件保存处');
INSERT INTO mtb_constants VALUES ('USER_PATH','HTML_PATH . USER_DIR',4,'用户文件保存处');
INSERT INTO mtb_constants VALUES ('USER_INC_PATH','USER_PATH . "include/"',5,'用户include file保存处');
INSERT INTO mtb_constants VALUES ('DB_ERROR_MAIL_TO','"error-ml@lockon.co.jp"',6,'DB错误邮件发送地址');
INSERT INTO mtb_constants VALUES ('DB_ERROR_MAIL_SUBJECT','"OS_TEST_ERROR"',7,'DB错误邮件事名');
INSERT INTO mtb_constants VALUES ('ZIP_DSN','DEFAULT_DSN',8,'邮政编码专用DB');
INSERT INTO mtb_constants VALUES ('USER_URL','SITE_URL . USER_DIR',9,'用户作成页等');
INSERT INTO mtb_constants VALUES ('AUTH_MAGIC','"31eafcbd7a81d7b401a7fdc12bba047c02d1fae6"',10,'认证用 magic');
INSERT INTO mtb_constants VALUES ('USER_TEMPLATE_DIR','"templates/"',16,'模板文件保存处');
INSERT INTO mtb_constants VALUES ('USER_PACKAGE_DIR','"packages/"',17,'模板文件保存处');
INSERT INTO mtb_constants VALUES ('USER_TEMPLATE_PATH','USER_PATH . USER_PACKAGE_DIR',18,'模板文件保存处');
INSERT INTO mtb_constants VALUES ('TEMPLATE_TEMP_DIR','HTML_PATH . "upload/temp_template/"',19,'模板文件一时保存处');
INSERT INTO mtb_constants VALUES ('USER_DEF_PHP','HTML_PATH . "__default.php"',20,'用户作成画面的默认PHP文件');
INSERT INTO mtb_constants VALUES ('DEF_LAYOUT','"products/list.php"',21,'其他画面的默认版面设计');
INSERT INTO mtb_constants VALUES ('MODULE_DIR','"downloads/module/"',22,'下载组件保存目录');
INSERT INTO mtb_constants VALUES ('MODULE_PATH','DATA_PATH . MODULE_DIR',23,'下载组件保存目录');
INSERT INTO mtb_constants VALUES ('UPDATE_DIR','"downloads/update/"',24,'HotFix保存目录');
INSERT INTO mtb_constants VALUES ('UPDATE_PATH','DATA_PATH . UPDATE_DIR',25,'HotFix保存目录');
INSERT INTO mtb_constants VALUES ('MAX_LIFETIME', '7200', 26, 'DBsession的有效期限(秒)');
INSERT INTO mtb_constants VALUES ('MASTER_DATA_DIR','DATA_PATH . "cache/"',27,'master datacache directory');
INSERT INTO mtb_constants VALUES ('UPDATE_HTTP','"http://sv01.ec-cube.net/info/index.php"',28,'更新管理用文件收藏地方');
INSERT INTO mtb_constants VALUES ('UPDATE_CSV_LINE_MAX','4096',29,'更新管理用CSV1行周围的最大字数');
INSERT INTO mtb_constants VALUES ('UPDATE_CSV_COL_MAX','13',30,'更新管理用CSVcolumn数');
INSERT INTO mtb_constants VALUES ('MODULE_CSV_COL_MAX','16',31,'组件管理用CSVcolumn数');
INSERT INTO mtb_constants VALUES ('EBIS_TAG_MID','1',32,'ebisutagu机能的组件ID');
INSERT INTO mtb_constants VALUES ('AFF_TAG_MID','3',33,'成果报酬型广告标记机能的组件ID');
INSERT INTO mtb_constants VALUES ('AFF_SHOPPING_COMPLETE','1',34,'商品购买完成');
INSERT INTO mtb_constants VALUES ('AFF_ENTRY_COMPLETE','2',35,'用户登记完成');
INSERT INTO mtb_constants VALUES ('CREDIT_HTTP_DOMAIN','"http://rcv.ec-cube.net/"',36,'结算接收用URL');
INSERT INTO mtb_constants VALUES ('CREDIT_HTTP_ANALYZE_PROGRAM','"rcv_credit.php"',37,'结算接收用URL');
INSERT INTO mtb_constants VALUES ('CREDIT_HTTP_ANALYZE_URL','CREDIT_HTTP_DOMAIN . CREDIT_HTTP_ANALYZE_PROGRAM',38,'结算接收用URL');
INSERT INTO mtb_constants VALUES ('CHAR_CODE','"UTF-8"',39,'字符编码');
INSERT INTO mtb_constants VALUES ('ECCUBE_PAYMENT','"EC-CUBE"',41,'结算组件给予文言');
INSERT INTO mtb_constants VALUES ('PEAR_DB_DEBUG','9',42,'PEAR::DB的debug mode');
INSERT INTO mtb_constants VALUES ('LOAD_BATCH_PASS','3600',43,'实行badge的最短的间隔(秒)');
INSERT INTO mtb_constants VALUES ('CLOSE_DAY','31',44,'结算日的是指定(最后一天的情况，请指定31。)');
INSERT INTO mtb_constants VALUES ('FAVORITE_ERROR','13',45,'普通网站错误');
INSERT INTO mtb_constants VALUES ('LIB_DIR','DATA_PATH . "lib/"',46,'程序库的传球');
INSERT INTO mtb_constants VALUES ('TTF_DIR','DATA_PATH . "fonts/"',47,'字体的传球');
INSERT INTO mtb_constants VALUES ('GRAPH_DIR','HTML_PATH . "upload/graph_image/"',48,'图表收藏目录');
INSERT INTO mtb_constants VALUES ('GRAPH_URL','URL_DIR . "upload/graph_image/"',49,'图表URL');
INSERT INTO mtb_constants VALUES ('GRAPH_PIE_MAX','10',50,'圆形图表最大表示数');
INSERT INTO mtb_constants VALUES ('GRAPH_LABEL_MAX','40',51,'图表的标签的文字数');
INSERT INTO mtb_constants VALUES ('PDF_DIR','DATA_PATH . "pdf/"',52,'PDF收藏目录');
INSERT INTO mtb_constants VALUES ('BAT_ORDER_AGE','70',53,'到(连)几岁作为总计的对象');
INSERT INTO mtb_constants VALUES ('PRODUCTS_TOTAL_MAX','15',54,'以商品总计到几位表示');
INSERT INTO mtb_constants VALUES ('DEFAULT_PRODUCT_DISP','2',55,'1:公开 2:非公开');
INSERT INTO mtb_constants VALUES ('DELIV_FREE_AMOUNT','0',56,'运费免费购买件数(是0的情况，买几个也不变得免费)');
INSERT INTO mtb_constants VALUES ('INPUT_DELIV_FEE','1',57,'发送费的设定画面表示(有效:1 无效:0)');
INSERT INTO mtb_constants VALUES ('OPTION_PRODUCT_DELIV_FEE','0',58,'每商品的运费设定(有效:1 无效:0)');
INSERT INTO mtb_constants VALUES ('OPTION_DELIV_FEE','1',59,'在每发送业者的发送费加在一起算(有效:1 无效:0)');
INSERT INTO mtb_constants VALUES ('OPTION_RECOMMEND','1',60, '推荐商品登记(有效:1 无效:0)');
INSERT INTO mtb_constants VALUES ('OPTION_CLASS_REGIST','1',61,'商品规格登记(有效:1 无效:0)');
INSERT INTO mtb_constants VALUES ('TV_IMAGE_WIDTH','170',62,'TV联锁商品画像横(侧)');
INSERT INTO mtb_constants VALUES ('TV_IMAGE_HEIGHT','95',63,'TV联锁商品画像纵');
INSERT INTO mtb_constants VALUES ('TV_PRODUCTS_MAX','10',64,'TV联锁商品最大登记数');
INSERT INTO mtb_constants VALUES ('DEFAULT_PASSWORD','"UAhgGR3L"',65,'会员登记变更(我的页)口令用');
INSERT INTO mtb_constants VALUES ('dtbDUCT_MAX','6',66,'推荐商品数');
INSERT INTO mtb_constants VALUES ('DELIV_ADDR_MAX','20',67,'另外的投送地点最大登记数');
INSERT INTO mtb_constants VALUES ('CUSTOMER_READING_MAX','30',68,'阅览履历保存数');
INSERT INTO mtb_constants VALUES ('ORDER_STATUS_MAX','50',70,'管理画面社会地位一览表示件数');
INSERT INTO mtb_constants VALUES ('REVIEW_REGIST_MAX','5',71,'服务台批评写入最大数');
INSERT INTO mtb_constants VALUES ('DEBUG_MODE','0',72,'输出debug mode(true:sfPrintR和DB的错误信息，false:不输出)');
INSERT INTO mtb_constants VALUES ('ADMIN_ID','"1"',73,'不被管理用户ID(支持用表示。)');
INSERT INTO mtb_constants VALUES ('CUSTOMER_CONFIRM_MAIL','0',74,'是不是会员登记的时候发送临时会员确认邮件(true:临时会员，false:本会员)');
INSERT INTO mtb_constants VALUES ('MELMAGA_SEND','1',75,'邮件杂志送信抑制(false:OFF，true:ON)');
INSERT INTO mtb_constants VALUES ('MELMAGA_BATCH_MODE','0',76,'邮件杂志batch mode(true:badge发送的 ※要cron设定，false:实时地发送)');
INSERT INTO mtb_constants VALUES ('LOGIN_FRAME','"login_frame.tpl"',77,'进入画面框架');
INSERT INTO mtb_constants VALUES ('MAIN_FRAME','"main_frame.tpl"',78,'管理画面框架');
INSERT INTO mtb_constants VALUES ('SITE_FRAME','"site_frame.tpl"',79,'普通网站画面框架');
INSERT INTO mtb_constants VALUES ('CERT_STRING','"7WDhcBTF"',80,'认证字符串');
INSERT INTO mtb_constants VALUES ('DUMMY_PASS','"########"',81,'假装递球口令');
INSERT INTO mtb_constants VALUES ('UNLIMITED','"++"',82,'库存数，表现销售限制无限。');
INSERT INTO mtb_constants VALUES ('BIRTH_YEAR','1901',83,'出生年月日登记开始年');
INSERT INTO mtb_constants VALUES ('RELEASE_YEAR','2005',84,'本系统的劳动开始年');
INSERT INTO mtb_constants VALUES ('CREDIT_ADD_YEAR','10',85,'信用卡的期限+几年');
INSERT INTO mtb_constants VALUES ('PARENT_CAT_MAX','12',86,'父母范畴的范畴ID的最大数(这个以下作为父母范畴。)');
INSERT INTO mtb_constants VALUES ('NUMBER_MAX','1000000000',87,'为了抵御GET价值变更等的恶作剧设置最大数限制。');
INSERT INTO mtb_constants VALUES ('POINT_RULE','2',88,'点的计算规则(1:四舍五入，2:切掉，3:结束)');
INSERT INTO mtb_constants VALUES ('POINT_VALUE','1',89,'每1点的价格(元)');
INSERT INTO mtb_constants VALUES ('ADMIN_MODE','0',90,'管理方式 1:有效0:无效(交货的时候)');
INSERT INTO mtb_constants VALUES ('DAILY_BATCH_MODE','0',91,'以销售额总计batch mode(true:badge合计的 ※要cron设定，false:实时地合计)');
INSERT INTO mtb_constants VALUES ('MAX_LOG_QUANTITY','5',92,'log file最大数(roguteshon)');
INSERT INTO mtb_constants VALUES ('MAX_LOG_SIZE','"1000000"',93,'1个log file保存的最大容量(byte)');
INSERT INTO mtb_constants VALUES ('TRANSACTION_ID_NAME','"transactionid"',94,'transactionID 的名字');
INSERT INTO mtb_constants VALUES ('FORGOT_MAIL','0',95,'发送口令忘记的确认邮件不同意吗？(0:不发送，1:发送)');
INSERT INTO mtb_constants VALUES ('HTML_TEMPLATE_SUB_MAX','12',96,'能登记的辅助商品的数');
INSERT INTO mtb_constants VALUES ('LINE_LIMIT_SIZE','60',97,'文字数太多的时候强制另起一行的尺寸(半角)');
INSERT INTO mtb_constants VALUES ('BIRTH_MONTH_POINT','0',98,'诞生日月点');
INSERT INTO mtb_constants VALUES ('CGI_DIR','HTML_PATH . "../cgi-bin/"',99,'信用卡(beritoransu)组件收藏目录');
INSERT INTO mtb_constants VALUES ('CGI_FILE','"mauthonly.cgi"',100,'核心CGI');
INSERT INTO mtb_constants VALUES ('ROOT_CATEGORY_1','2',101,'途径范畴ID');
INSERT INTO mtb_constants VALUES ('ROOT_CATEGORY_2','3',102,'途径范畴ID');
INSERT INTO mtb_constants VALUES ('ROOT_CATEGORY_3','4',103,'途径范畴ID');
INSERT INTO mtb_constants VALUES ('ROOT_CATEGORY_4','5',104,'途径范畴ID');
INSERT INTO mtb_constants VALUES ('ROOT_CATEGORY_5','6',105,'途径范畴ID');
INSERT INTO mtb_constants VALUES ('ROOT_CATEGORY_6','7',106,'途径范畴ID');
INSERT INTO mtb_constants VALUES ('ROOT_CATEGORY_7','8',107,'途径范畴ID');
INSERT INTO mtb_constants VALUES ('PAYMENT_CREDIT_ID','1',108,'信用卡');
INSERT INTO mtb_constants VALUES ('PAYMENT_CONVENIENCE_ID','2',109,'便利店支付');
INSERT INTO mtb_constants VALUES ('LARGE_IMAGE_WIDTH','500',110,'扩大画像横(侧)');
INSERT INTO mtb_constants VALUES ('LARGE_IMAGE_HEIGHT','500',111,'扩大画像纵');
INSERT INTO mtb_constants VALUES ('SMALL_IMAGE_WIDTH','130',112,'一览画像横(侧)');
INSERT INTO mtb_constants VALUES ('SMALL_IMAGE_HEIGHT','130',113,'一览画像纵');
INSERT INTO mtb_constants VALUES ('NORMAL_IMAGE_WIDTH','260',114,'通常画像横(侧)');
INSERT INTO mtb_constants VALUES ('NORMAL_IMAGE_HEIGHT','260',115,'通常画像纵');
INSERT INTO mtb_constants VALUES ('NORMAL_SUBIMAGE_WIDTH','200',116,'通常辅助画像横(侧)');
INSERT INTO mtb_constants VALUES ('NORMAL_SUBIMAGE_HEIGHT','200',117,'通常辅助画像纵');
INSERT INTO mtb_constants VALUES ('LARGE_SUBIMAGE_WIDTH','500',118,'扩大辅助画像横(侧)');
INSERT INTO mtb_constants VALUES ('LARGE_SUBIMAGE_HEIGHT','500',119,'扩大辅助画像纵');
INSERT INTO mtb_constants VALUES ('DISP_IMAGE_WIDTH','65',120,'一览表示画像横(侧)');
INSERT INTO mtb_constants VALUES ('DISP_IMAGE_HEIGHT','65',121,'一览表示画像纵');
INSERT INTO mtb_constants VALUES ('OTHER_IMAGE1_WIDTH','500',122,'其他的画像1');
INSERT INTO mtb_constants VALUES ('OTHER_IMAGE1_HEIGHT','500',123,'其他的画像1');
INSERT INTO mtb_constants VALUES ('HTMLMAIL_IMAGE_WIDTH','110',124,'ＨＴＭＬ邮件模板邮件担当画像横(侧)');
INSERT INTO mtb_constants VALUES ('HTMLMAIL_IMAGE_HEIGHT','120',125,'ＨＴＭＬ邮件模板邮件担当画像纵');
INSERT INTO mtb_constants VALUES ('IMAGE_SIZE','1000',126,'画像尺寸限制(KB)');
INSERT INTO mtb_constants VALUES ('CSV_SIZE','2000',127,'CSV尺寸限制(KB)');
INSERT INTO mtb_constants VALUES ('CSV_LINE_MAX','10000',128,'每CSV上载1行的最大字数');
INSERT INTO mtb_constants VALUES ('PDF_SIZE','5000',129,'PDF尺寸限制(KB):商品详细文件等');
INSERT INTO mtb_constants VALUES ('FILE_SIZE','10000',130,'文件管理画面提高限制(KB)');
INSERT INTO mtb_constants VALUES ('TEMPLATE_SIZE','10000',131,'能提高的模板文件限制(KB)');
INSERT INTO mtb_constants VALUES ('LEVEL_MAX','5',132,'范畴的最大阶层');
INSERT INTO mtb_constants VALUES ('CATEGORY_MAX','1000',133,'最大范畴登记数');
INSERT INTO mtb_constants VALUES ('ADMIN_TITLE','"EC网站管理页"',134,'管理页标题');
INSERT INTO mtb_constants VALUES ('SELECT_RGB','"#ffffdf"',135,'编辑的时候强调表示颜色');
INSERT INTO mtb_constants VALUES ('DISABLED_RGB','"#C9C9C9"',136,'输入项目无效的时候的表示颜色');
INSERT INTO mtb_constants VALUES ('ERR_COLOR','"#ffe8e8"',137,'错误的时候表示颜色');
INSERT INTO mtb_constants VALUES ('CATEGORY_HEAD','">"',138,'父母范畴表示文字');
INSERT INTO mtb_constants VALUES ('START_BIRTH_YEAR','1901',139,'出生年月日选择开始年');
INSERT INTO mtb_constants VALUES ('NORMAL_PRICE_TITLE','"通常价格"',140,'价格名称');
INSERT INTO mtb_constants VALUES ('SALE_PRICE_TITLE','"销售价格"',141,'价格名称');
INSERT INTO mtb_constants VALUES ('LOG_PATH','DATA_PATH . "logs/site.log"',142,'log file');
INSERT INTO mtb_constants VALUES ('CUSTOMER_LOG_PATH','DATA_PATH . "logs/customer.log"',143,'会员进入 log file');
INSERT INTO mtb_constants VALUES ('IMAGE_TEMP_DIR','HTML_PATH . "upload/temp_image/"',150,'画像一时保存');
INSERT INTO mtb_constants VALUES ('IMAGE_SAVE_DIR','HTML_PATH . "upload/save_image/"',151,'画像保存处');
INSERT INTO mtb_constants VALUES ('IMAGE_TEMP_URL','URL_DIR . "upload/temp_image/"',152,'画像一时保存URL');
INSERT INTO mtb_constants VALUES ('IMAGE_SAVE_URL','URL_DIR . "upload/save_image/"',153,'画像保存处URL');
INSERT INTO mtb_constants VALUES ('IMAGE_TEMP_URL_RSS','SITE_URL . "upload/temp_image/"',154,'RSS用画像一时保存URL');
INSERT INTO mtb_constants VALUES ('IMAGE_SAVE_URL_RSS','SITE_URL . "upload/save_image/"',155,'RSS用画像保存处URL');
INSERT INTO mtb_constants VALUES ('CSV_TEMP_DIR','HTML_PATH . "upload/csv/"',156,'编码CSV的一时保存处');
INSERT INTO mtb_constants VALUES ('NO_IMAGE_URL','URL_DIR . "misc/blank.gif"',157,'没有画像的情况表示');
INSERT INTO mtb_constants VALUES ('NO_IMAGE_DIR','HTML_PATH . "misc/blank.gif"',158,'没有画像的情况表示');
INSERT INTO mtb_constants VALUES ('URL_SYSTEM_TOP','URL_DIR . "admin/system/index.php"',159,'系统管理首位');
INSERT INTO mtb_constants VALUES ('URL_CLASS_REGIST','URL_DIR . "admin/products/class.php"',160,'规格登记');
INSERT INTO mtb_constants VALUES ('URL_INPUT_ZIP','URL_DIR . "input_zip.php"',161,'邮政编码输入');
INSERT INTO mtb_constants VALUES ('URL_DELIVERY_TOP','URL_DIR . "admin/basis/delivery.php"',162,'发送业者登记');
INSERT INTO mtb_constants VALUES ('URL_PAYMENT_TOP','URL_DIR . "admin/basis/payment.php"',163,'支付方法登记');
INSERT INTO mtb_constants VALUES ('URL_CONTROL_TOP','URL_DIR . "admin/basis/control.php"',164,'网站管理信息登记');
INSERT INTO mtb_constants VALUES ('URL_HOME','URL_DIR . "admin/home.php"',165,'月台');
INSERT INTO mtb_constants VALUES ('URL_LOGIN','URL_DIR . "admin/index.php"',166,'进入页');
INSERT INTO mtb_constants VALUES ('URL_SEARCH_TOP','URL_DIR . "admin/products/index.php"',167,'商品检索页');
INSERT INTO mtb_constants VALUES ('URL_ORDER_EDIT','URL_DIR . "admin/order/edit.php"',168,'定购编辑页');
INSERT INTO mtb_constants VALUES ('URL_SEARCH_ORDER','URL_DIR . "admin/order/index.php"',169,'定购编辑页');
INSERT INTO mtb_constants VALUES ('URL_ORDER_MAIL','URL_DIR . "admin/order/mail.php"',170,'定购编辑页');
INSERT INTO mtb_constants VALUES ('URL_LOGOUT','URL_DIR . "admin/logout.php"',171,'退出页');
INSERT INTO mtb_constants VALUES ('URL_SYSTEM_CSV','URL_DIR . "admin/system/member_csv.php"',172,'系统管理CSV输出页');
INSERT INTO mtb_constants VALUES ('URL_ADMIN_CSS','URL_DIR . "admin/css/"',173,'管理页用CSS保管目录');
INSERT INTO mtb_constants VALUES ('URL_CAMPAIGN_TOP','URL_DIR . "admin/contents/campaign.php"',174,'运动登记页');
INSERT INTO mtb_constants VALUES ('URL_CAMPAIGN_DESIGN','URL_DIR . "admin/contents/campaign_design.php"',175,'运动设计设定页');
INSERT INTO mtb_constants VALUES ('SUCCESS','0',176,'访问成功');
INSERT INTO mtb_constants VALUES ('LOGIN_ERROR','1',177,'进入失败');
INSERT INTO mtb_constants VALUES ('ACCESS_ERROR','2',178,'访问失败(暂停等)');
INSERT INTO mtb_constants VALUES ('AUTH_ERROR','3',179,'存取权交货期限违反');
INSERT INTO mtb_constants VALUES ('INVALID_MOVE_ERRORR','4',180,'不正当的变迁错误');
INSERT INTO mtb_constants VALUES ('PRODUCTS_LIST_MAX','15',181,'商品一览表示数');
INSERT INTO mtb_constants VALUES ('MEMBER_PMAX','10',182,'前往成员管理页表示数');
INSERT INTO mtb_constants VALUES ('SEARCH_PMAX','10',183,'前往检索页表示数');
INSERT INTO mtb_constants VALUES ('NAVI_PMAX','4',184,'页号码的最大表示件数');
INSERT INTO mtb_constants VALUES ('PRODUCTSUB_MAX','5',185,'商品辅助信息最大数');
INSERT INTO mtb_constants VALUES ('DELIVTIME_MAX','16',186,'发送时间的最大表示数');
INSERT INTO mtb_constants VALUES ('DELIVFEE_MAX','47',187,'发送费用的最大表示数');
INSERT INTO mtb_constants VALUES ('STEXT_LEN','50',188,'短的项目的文字数(名字等)');
INSERT INTO mtb_constants VALUES ('SMTEXT_LEN','100',189,'中长的项目的文字数');
INSERT INTO mtb_constants VALUES ('MTEXT_LEN','200',190,'长的项目的文字数(地址等)');
INSERT INTO mtb_constants VALUES ('MLTEXT_LEN','1000',191,'长中文的文字数(咨询等)');
INSERT INTO mtb_constants VALUES ('LTEXT_LEN','3000',192,'长篇文章的文字数');
INSERT INTO mtb_constants VALUES ('LLTEXT_LEN','99999',193,'超长篇文章的文字数(邮件杂志等)');
INSERT INTO mtb_constants VALUES ('URL_LEN','300',194,'URL的文字长');
INSERT INTO mtb_constants VALUES ('ID_MAX_LEN','15',195,'ID·口令的文字数限制');
INSERT INTO mtb_constants VALUES ('ID_MIN_LEN','4',196,'ID·口令的文字数限制');
INSERT INTO mtb_constants VALUES ('PRICE_LEN','8',197,'金额横梁数');
INSERT INTO mtb_constants VALUES ('PERCENTAGE_LEN','3',198,'比率横梁数');
INSERT INTO mtb_constants VALUES ('AMOUNT_LEN','6',199,'库存数，销售限制数');
INSERT INTO mtb_constants VALUES ('ZIP01_LEN','3',200,'邮政编码1');
INSERT INTO mtb_constants VALUES ('ZIP02_LEN','4',201,'邮政编码2');
INSERT INTO mtb_constants VALUES ('TEL_ITEM_LEN','6',202,'电话号码各项目限制');
INSERT INTO mtb_constants VALUES ('TEL_LEN','12',203,'电话号码总数');
INSERT INTO mtb_constants VALUES ('PASSWORD_LEN1','4',204,'口令1');
INSERT INTO mtb_constants VALUES ('PASSWORD_LEN2','10',205,'口令2');
INSERT INTO mtb_constants VALUES ('INT_LEN','8',206,'检验数值用横梁数(INT)');
INSERT INTO mtb_constants VALUES ('CREDIT_NO_LEN','4',207,'信用卡的文字数');
INSERT INTO mtb_constants VALUES ('SEARCH_CATEGORY_LEN','18',208,'检索范畴最大表示文字数(byte)');
INSERT INTO mtb_constants VALUES ('FILE_NAME_LEN','10',209,'文件名表示文字数');
INSERT INTO mtb_constants VALUES ('SALE_LIMIT_MAX','10',210,'没有是购买限制的情况的最大购买件数');
INSERT INTO mtb_constants VALUES ('SITE_TITLE','"EC-CUBE 试验网站"',211,'HTML标题');
INSERT INTO mtb_constants VALUES ('COOKIE_EXPIRE','365',212,'小甜饼干保持期限(星期日)');
INSERT INTO mtb_constants VALUES ('PRODUCT_NOT_FOUND','1',213,'没有指定商品页');
INSERT INTO mtb_constants VALUES ('CART_EMPTY','2',214,'手推车内天空');
INSERT INTO mtb_constants VALUES ('PAGE_ERROR','3',215,'页推移错误');
INSERT INTO mtb_constants VALUES ('CART_ADD_ERROR','4',216,'购买处理中的手推车商品追加错误');
INSERT INTO mtb_constants VALUES ('CANCEL_PURCHASE','5',217,'如果其他购买手续也能进行了');
INSERT INTO mtb_constants VALUES ('CATEGORY_NOT_FOUND','6',218,'没有指定范畴页');
INSERT INTO mtb_constants VALUES ('SITE_LOGIN_ERROR','7',219,'进入失败');
INSERT INTO mtb_constants VALUES ('CUSTOMER_ERROR','8',220,'对会员专用页的访问错误');
INSERT INTO mtb_constants VALUES ('SOLD_OUT','9',221,'购买的时候的全部售完错误');
INSERT INTO mtb_constants VALUES ('CART_NOT_FOUND','10',222,'手推车内商品的读包含在内错误');
INSERT INTO mtb_constants VALUES ('LACK_POINT','11',223,'点的不足');
INSERT INTO mtb_constants VALUES ('TEMP_LOGIN_ERROR','12',224,'临时登记人进入失败');
INSERT INTO mtb_constants VALUES ('URL_ERROR','13',225,'URL错误');
INSERT INTO mtb_constants VALUES ('EXTRACT_ERROR','14',226,'文件解冻错误');
INSERT INTO mtb_constants VALUES ('FTP_DOWNLOAD_ERROR','15',227,'FTP下载错误');
INSERT INTO mtb_constants VALUES ('FTP_LOGIN_ERROR','16',228,'FTP进入错误');
INSERT INTO mtb_constants VALUES ('FTP_CONNECT_ERROR','17',229,'FTP连接错误');
INSERT INTO mtb_constants VALUES ('CREATE_DB_ERROR','18',230,'DB作成错误');
INSERT INTO mtb_constants VALUES ('DB_IMPORT_ERROR','19',231,'DB进口错误');
INSERT INTO mtb_constants VALUES ('FILE_NOT_FOUND','20',232,'设定文件存在错误');
INSERT INTO mtb_constants VALUES ('WRITE_FILE_ERROR','21',233,'写错误');
INSERT INTO mtb_constants VALUES ('FREE_ERROR_MSG','999',234,'自由消息');
INSERT INTO mtb_constants VALUES ('SEPA_CATNAVI','" > "',235,'范畴段落文字');
INSERT INTO mtb_constants VALUES ('SEPA_CATLIST','" | "',236,'范畴段落文字');
INSERT INTO mtb_constants VALUES ('URL_SHOP_TOP','SSL_URL . "shopping/index.php"',237,'会员信息输入');
INSERT INTO mtb_constants VALUES ('URL_ENTRY_TOP','SSL_URL . "entry/index.php"',238,'会员登记页TOP');
INSERT INTO mtb_constants VALUES ('URL_SITE_TOP','URL_DIR . "index.php"',239,'网站首位');
INSERT INTO mtb_constants VALUES ('URL_CART_TOP','URL_DIR . "cart/index.php"',240,'手推车首位');
INSERT INTO mtb_constants VALUES ('URL_DELIV_TOP','URL_DIR . "shopping/deliv.php"',241,'发送时间设定');
INSERT INTO mtb_constants VALUES ('URL_MYPAGE_TOP','SSL_URL . "mypage/login.php"',242,'我的页首');
INSERT INTO mtb_constants VALUES ('URL_SHOP_CONFIRM','URL_DIR . "shopping/confirm.php"',243,'购买确认页');
INSERT INTO mtb_constants VALUES ('URL_SHOP_PAYMENT','URL_DIR . "shopping/payment.php"',244,'支付方法选择页');
INSERT INTO mtb_constants VALUES ('URL_SHOP_COMPLETE','URL_DIR . "shopping/complete.php"',245,'购买完成画面');
INSERT INTO mtb_constants VALUES ('URL_SHOP_CREDIT','URL_DIR . "shopping/card.php"',246,'卡结算画面');
INSERT INTO mtb_constants VALUES ('URL_SHOP_LOAN','URL_DIR . "shopping/loan.php"',247,'贷款结算画面');
INSERT INTO mtb_constants VALUES ('URL_SHOP_CONVENIENCE','URL_DIR . "shopping/convenience.php"',248,'便利店支付画面');
INSERT INTO mtb_constants VALUES ('URL_SHOP_MODULE','URL_DIR . "shopping/load_payment_module.php"',249,'组件追加用画面');
INSERT INTO mtb_constants VALUES ('URL_PRODUCTS_TOP','URL_DIR . "products/top.php"',250,'商品首位');
INSERT INTO mtb_constants VALUES ('LIST_P_HTML','URL_DIR . "products/list-p"',251,'商品一览(HTML输出)');
INSERT INTO mtb_constants VALUES ('LIST_C_HTML','URL_DIR . "products/list.php?mode=search&category_id="',252,'商品一览(HTML输出)');
INSERT INTO mtb_constants VALUES ('DETAIL_P_HTML','URL_DIR . "products/detail.php?product_id="',253,'商品详细(HTML输出)');
INSERT INTO mtb_constants VALUES ('MYPAGE_DELIVADDR_URL','URL_DIR . "mypage/delivery.php"',254,'我的页投送地点URL');
INSERT INTO mtb_constants VALUES ('MAIL_TYPE_PC','1',255,'邮件地址类别');
INSERT INTO mtb_constants VALUES ('MAIL_TYPE_MOBILE','2',256,'邮件地址类别');
INSERT INTO mtb_constants VALUES ('ORDER_NEW','1',257,'新规章定购');
INSERT INTO mtb_constants VALUES ('ORDER_PAY_WAIT','2',258,'入款等候');
INSERT INTO mtb_constants VALUES ('ORDER_PRE_END','6',259,'入款完毕');
INSERT INTO mtb_constants VALUES ('ORDER_CANCEL','3',260,'废除');
INSERT INTO mtb_constants VALUES ('ORDER_BACK_ORDER','4',261,'寄送中');
INSERT INTO mtb_constants VALUES ('ORDER_DELIV','5',262,'发送完毕');
INSERT INTO mtb_constants VALUES ('ODERSTATUS_COMMIT','ORDER_DELIV',263,'接受订货社会地位变更时候点等加在一起算的社会地位号码(发送完毕)');
INSERT INTO mtb_constants VALUES ('ADMIN_NEWS_STARTYEAR','2005',264,'新到信息管理画面开始年(西历)');
INSERT INTO mtb_constants VALUES ('ENTRY_CUSTOMER_TEMP_SUBJECT','"会员临时登记完成了。"',265,'会员登记');
INSERT INTO mtb_constants VALUES ('ENTRY_CUSTOMER_REGIST_SUBJECT','"本会员登记完成了。"',266,'会员登记');
INSERT INTO mtb_constants VALUES ('ENTRY_LIMIT_HOUR','1',267,'再入会限制时间(单位:时间)');
INSERT INTO mtb_constants VALUES ('RECOMMEND_NUM','8',268,'推荐商品表示数');
INSERT INTO mtb_constants VALUES ('BEST_MAX','5',269,'最佳商品的最大登记数');
INSERT INTO mtb_constants VALUES ('BEST_MIN','3',270,'最佳商品的最小登记数(登记数不满的情况不表示。)');
INSERT INTO mtb_constants VALUES ('DELIV_DATE_END_MAX','21',271,'投递可能的日期以后的pull-down表示最大日数');
INSERT INTO mtb_constants VALUES ('PURCHASE_CUSTOMER_REGIST','0',272,'购买的时候强制会员登记(1:有效 0:无效)');
INSERT INTO mtb_constants VALUES ('RELATED_PRODUCTS_MAX','3',273,'买了这个商品的人这样的商品也买着的 表示件数');
INSERT INTO mtb_constants VALUES ('CV_PAYMENT_LIMIT','14',274,'支付期限');
INSERT INTO mtb_constants VALUES ('CAMPAIGN_REGIST_MAX','20',275,'运动登记最大数');
INSERT INTO mtb_constants VALUES ('REVIEW_ALLOW_URL','0',276,'由于商品批评准许URL写入不同意吗');
INSERT INTO mtb_constants VALUES ('TRACKBACK_STATUS_VIEW','1',277,'拉镜头 表示');
INSERT INTO mtb_constants VALUES ('TRACKBACK_STATUS_NOT_VIEW','2',278,'拉镜头 非表示');
INSERT INTO mtb_constants VALUES ('TRACKBACK_STATUS_SPAM','3',279,'拉镜头 垃圾邮件');
INSERT INTO mtb_constants VALUES ('TRACKBACK_VIEW_MAX','10',280,'服务台最大表示数');
INSERT INTO mtb_constants VALUES ('TRACKBACK_TO_URL','SITE_URL . "tb/index.php?pid="',281,'拉镜头处URL');
INSERT INTO mtb_constants VALUES ('SITE_CONTROL_TRACKBACK','1',282,'网站管理 拉镜头');
INSERT INTO mtb_constants VALUES ('SITE_CONTROL_AFFILIATE','2',283,'网站管理 成果报酬型广告');
INSERT INTO mtb_constants VALUES ('MAIL_BACKEND','"smtp"',284,'Pear::Mail back-end:mail|smtp|sendmail');
INSERT INTO mtb_constants VALUES ('OS_TYPE','"LINUX"',285,'OS类别:WIN|LINUX');
INSERT INTO mtb_constants VALUES ('SMTP_HOST','"127.0.0.1"',286,'SMTP服务器');
INSERT INTO mtb_constants VALUES ('SMTP_PORT','"25"',287,'SMTP端口');
INSERT INTO mtb_constants VALUES ('DEFAULT_TEMPLATE_NAME', '"default"', 300,'默认模板名');
INSERT INTO mtb_constants VALUES ('TEMPLATE_NAME', 'DEFAULT_TEMPLATE_NAME', 301,'模板名');
INSERT INTO mtb_constants VALUES ('SMARTY_TEMPLATES_DIR',' DATA_PATH . "Smarty/templates/"', 302,'SMARTY模板');
INSERT INTO mtb_constants VALUES ('TPL_DIR','URL_DIR . USER_DIR . USER_PACKAGE_DIR . TEMPLATE_NAME . "/"', 303,'SMARTY模板');
INSERT INTO mtb_constants VALUES ('TEMPLATE_DIR','SMARTY_TEMPLATES_DIR . TEMPLATE_NAME . "/"', 304,'SMARTY模板');
INSERT INTO mtb_constants VALUES ('TEMPLATE_ADMIN_DIR','TEMPLATE_DIR . "admin/"', 305,'SMARTY模板(管理页)');
INSERT INTO mtb_constants VALUES ('COMPILE_DIR','DATA_PATH . "Smarty/templates_c/" . TEMPLATE_NAME . "/"',306,'SMARTY编译');
INSERT INTO mtb_constants VALUES ('COMPILE_ADMIN_DIR','COMPILE_DIR . "admin/"',307,'SMARTY编译(管理页)');
INSERT INTO mtb_constants VALUES ('TEMPLATE_FTP_DIR','USER_PATH . USER_PACKAGE_DIR . TEMPLATE_NAME . "/"', 308,'SMARTY模板(FTP许可)');
INSERT INTO mtb_constants VALUES ('COMPILE_FTP_DIR','COMPILE_DIR . USER_DIR', 309,'SMARTY模板(FTP许可)');
INSERT INTO mtb_constants VALUES ('BLOC_DIR','"bloc/"', 310,'块文件保存处');
INSERT INTO mtb_constants VALUES ('BLOC_PATH','TEMPLATE_DIR . BLOC_DIR', 311,'块文件保存处');
INSERT INTO mtb_constants VALUES ('CAMPAIGN_DIR','"cp/"',312,'运动文件保存处');
INSERT INTO mtb_constants VALUES ('CAMPAIGN_URL','URL_DIR . CAMPAIGN_DIR',313,'运动关联');
INSERT INTO mtb_constants VALUES ('CAMPAIGN_PATH','HTML_PATH . CAMPAIGN_DIR',314,'运动关联');
INSERT INTO mtb_constants VALUES ('CAMPAIGN_TEMPLATE_DIR','"campaign/"',315,'运动关联');
INSERT INTO mtb_constants VALUES ('CAMPAIGN_TEMPLATE_PATH','TEMPLATE_DIR . CAMPAIGN_TEMPLATE_DIR',316,'运动关联');
INSERT INTO mtb_constants VALUES ('CAMPAIGN_BLOC_DIR','"bloc/"',317,'运动关联');
INSERT INTO mtb_constants VALUES ('CAMPAIGN_BLOC_PATH','CAMPAIGN_TEMPLATE_PATH . CAMPAIGN_BLOC_DIR',318,'运动关联');
INSERT INTO mtb_constants VALUES ('CAMPAIGN_TEMPLATE_ACTIVE','"active/"',319,'运动关联');
INSERT INTO mtb_constants VALUES ('CAMPAIGN_TEMPLATE_END','"end/"',320,'运动关联');
INSERT INTO mtb_constants VALUES ('MOBILE_TEMPLATE_DIR', 'TEMPLATE_DIR . "mobile/"', 400,'SMARTY模板(mobile)');
INSERT INTO mtb_constants VALUES ('MOBILE_COMPILE_DIR', 'COMPILE_DIR . "mobile/"', 401,'SMARTY编译(mobile)');
INSERT INTO mtb_constants VALUES ('MOBILE_SESSION_LIFETIME', '1800', 402,'session的继续存在时间(秒)');
INSERT INTO mtb_constants VALUES ('MOBILE_USE_KARA_MAIL', 'false', 403,'是不是使用天空邮件机能');
INSERT INTO mtb_constants VALUES ('MOBILE_KARA_MAIL_ADDRESS_USER', '"eccube"', 404,'天空邮件接待地址的用户注册名部分');
INSERT INTO mtb_constants VALUES ('MOBILE_KARA_MAIL_ADDRESS_DELIMITER', '"+"', 405,'是天空邮件接待地址的用户注册名和指令之间的段落文字 qmail 的情况 -');
INSERT INTO mtb_constants VALUES ('MOBILE_KARA_MAIL_ADDRESS_DOMAIN', '"mobile.ec-cube.net"', 406,'天空邮件接待地址的域部分');
INSERT INTO mtb_constants VALUES ('MOBILE_ADDITIONAL_MAIL_DOMAINS', '"rebelt.co.jp, lockon.co.jp"', 407,'不是手机的邮件地址,不过，看作是手机的域的名单 任意的数的「,」「」断开。');
INSERT INTO mtb_constants VALUES ('MOBILE_IMAGE_DIR', 'HTML_PATH . "upload/mobile_image"', 408,'面向手机变换画像保存目录');
INSERT INTO mtb_constants VALUES ('MOBILE_IMAGE_URL', 'URL_DIR . "upload/mobile_image"', 409,'面向手机变换画像保存目录');
INSERT INTO mtb_constants VALUES ('MOBILE_URL_SITE_TOP', 'MOBILE_URL_DIR . "index.php"', 410,'移动URL');
INSERT INTO mtb_constants VALUES ('MOBILE_URL_CART_TOP', 'MOBILE_URL_DIR . "cart/index.php"', 411,'手推车首位');
INSERT INTO mtb_constants VALUES ('MOBILE_URL_SHOP_TOP', 'MOBILE_SSL_URL . "shopping/index.php"', 412,'会员信息输入');
INSERT INTO mtb_constants VALUES ('MOBILE_URL_SHOP_CONFIRM', 'MOBILE_URL_DIR . "shopping/confirm.php"', 413,'购买确认页');
INSERT INTO mtb_constants VALUES ('MOBILE_URL_SHOP_PAYMENT', 'MOBILE_URL_DIR . "shopping/payment.php"', 414,'支付方法选择页');
INSERT INTO mtb_constants VALUES ('MOBILE_DETAIL_P_HTML', 'MOBILE_URL_DIR . "products/detail.php?product_id="', 415,'商品详细(HTML输出)');
INSERT INTO mtb_constants VALUES ('MOBILE_URL_SHOP_COMPLETE', 'MOBILE_URL_DIR . "shopping/complete.php"', 416,'购买完成画面');
INSERT INTO mtb_constants VALUES ('MOBILE_URL_SHOP_MODULE', 'MOBILE_URL_DIR . "shopping/load_payment_module.php"', 417,'组件追加用画面');
INSERT INTO mtb_constants VALUES ('OSTORE_URL', '"http://store.ec-cube.net/"', 500, '所有者店铺URL');
INSERT INTO mtb_constants VALUES ('OSTORE_SSLURL', '"https://store.ec-cube.net/"', 501, '所有者店铺URL');
INSERT INTO mtb_constants VALUES ('OSTORE_LOG_PATH', 'DATA_PATH . "logs/ownersstore.log"', 502, '所有者店铺对数(记录)传球');
INSERT INTO mtb_constants VALUES ('OSTORE_STATUS_ERROR', '"ERROR"', 503, '所有者店铺通讯社会地位');
INSERT INTO mtb_constants VALUES ('OSTORE_STATUS_SUCCESS', '"SUCCESS"', 504, '所有者店铺通讯社会地位');
INSERT INTO mtb_constants VALUES ('OSTORE_E_UNKNOWN', '"1000"', 505, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_INVALID_PARAM', '"1001"', 506, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_NO_CUSTOMER', '"1002"', 507, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_WRONG_URL_PASS', '"1003"', 508, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_NO_PRODUCTS', '"1004"', 509, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_NO_DL_DATA', '"1005"', 510, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_DL_DATA_OPEN', '"1006"', 511, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_DLLOG_AUTH', '"1007"', 512, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_C_ADMIN_AUTH', '"2001"', 513, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_C_HTTP_REQ', '"2002"', 514, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_C_HTTP_RESP', '"2003"', 515, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_C_FAILED_JSON_PARSE', '"2004"', 516, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_C_NO_KEY', '"2005"', 517, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_C_INVALID_ACCESS', '"2006"', 518, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_C_INVALID_PARAM', '"2007"', 519, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_C_AUTOUP_DISABLE', '"2008"', 520, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_C_PERMISSION', '"2009"', 521, '所有者店铺通讯错误码');
INSERT INTO mtb_constants VALUES ('OSTORE_E_C_BATCH_ERR', '"2010"', 522, '所有者店铺通讯错误码');

INSERT INTO dtb_module (module_id,module_code,module_name,update_date)values(0,0,'patch',now());